#**********************************************************#
#                      == Deployment ==                    #
#**********************************************************#
######---类型设置 (可选为Deployment、StatefulSet，默认为：Deployment)---######
kind: Deployment

######---镜像设置---######
image:
  repository: "mydlqclub/springboot-helloworld"
  tag: "0.0.1"
  pullPolicy: "IfNotPresent"

######---副本数设置---######
replicas: 1

######---更新策略---####
updateStrategy:
  type: RollingUpdate

######---重启策略---(Always、OnFailure、Never)####
restartPolicy: Always

######---Resources资源限制设置---######
resources:
  limits:
    memory: 512Mi
    cpu: 1000m
  requests:
    memory: 256Mi
    cpu: 500m

######---Pod podAnnotations设置---######
podAnnotations:
#  prometheus.io/scrape: "true"
#  prometheus.io/port: "9030"
#  prometheus.io/path: "/"

######---terminationGracePeriodSeconds优雅关闭Pod设置(默认30s)---######
terminationGracePeriodSeconds: 10

######---环境变量ENV设置---######
env: 
  - name: "JAVA_OPTS"
    value: "-Dserver.port=8080"
  - name: "APP_OPTS"
    value: "" 

######---环境变量EnvFrom设置---######
envFrom:
  #- configMapRef:
  #    name: env-config

######---Port端口设置---######
ports: 
  - name: server
    containerPort: 8080
    protocol: TCP
  - name: management
    containerPort: 8081
    protocol: TCP

######---ServiceAccount---#####
#serviceAccountName: default   

######---Read && Live 探针设置---######
# probe:
#   port: 8081
#   path: /actuator/health
#   livenessProbe:
#     initialDelaySeconds: 40
#     periodSeconds: 10
#     successThreshold: 1
#     failureThreshold: 10
#     timeoutSeconds: 15
#   readinessProbe:
#     initialDelaySeconds: 30
#     periodSeconds: 10
#     successThreshold: 1
#     failureThreshold: 10
#     timeoutSeconds: 15
   
######---启动节点设置设置---######
nodeSelector: 
  # selectNode: master

######---Volume && VolumeMounts设置---######
mount:
  #######---volumeMounts---######  
  # volumeMounts: 
  #   - name: spring-app-config
  #     mountPath: /opt/deployments/config
  #     readOnly: true
  #######---volumes---######     
  # volumes: 
  #   - name: spring-app-config
  #     configMap:
  #       name: config
  #       items:
  #       - key: application.yml
  #         path: application.yml
  #   - name: datadir
  #     persistentVolumeClaim:
  #       claimName: datadir-pvc
  #######---volumeClaimTemplates---###### 
  # volumeClaimTemplates: #(部署类型必须是：StatefulSet)
  #   - metadata:
  #       name: www
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       volumeMode: Filesystem
  #       resources:
  #         requests:
  #           storage: 50Mi
  #       storageClassName: local-storage

######---Affinity设置---######
affinity: 
  # nodeAffinity: 
  #   #节点亲和性
  #   requiredDuringSchedulingIgnoredDuringExecution:  #硬策略
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: NotIn
  #         values:
  #         - k8s-node-2-12
  #   preferredDuringSchedulingIgnoredDuringExecution: #软策略
  #   - weight: 1   #取值范围1-100
  #     preference:
  #       matchExpressions:
  #       - key: kube
  #         operator: In
  #         values:
  #         - test

######---Tolerations容忍设置---######
tolerations: 
  # - operator: "Exists"

#**********************************************************#
#                      == Service ==                       #
#**********************************************************#

service:
  ######---Service type设置 (可以设置为ClusterIP、NodePort、None)---######
  type: ClusterIP
   ######---Service Labels设置---######
  labels: 
    # svcEndpoints: actuator
  ######---Service Annotations设置---######
  annotations: {}
  ######---Service Ports设置---######
  ports: 
    - name: server
      port: 8080
      targetPort: 8080
      protocol: TCP
      # 如果type为NodePort,则可以设置下面的nodePort端口,否则请不要设置
      # nodePort: 30080 
    - name: management
      port: 8081
      targetPort: 8081
      protocol: TCP
      # 如果type为NodePort,则可以设置下面的nodePort端口,否则请不要设置
      # nodePort: 30081

#**********************************************************#
#                      == Ingress ==                       #
#**********************************************************#

ingress:
  ## 是否启动 Ingress
  enabled: false
  ## 设置域名
  hostname: www.mydlq.club
  ## 路径设置
  path: /
  ## 服务名称设置
  service: test
  ## 端口设置
  port: server
  ## 设置 Ingress Annotations
  annotations: {}
  #  kubernetes.io/ingress.class: traefik

  ## 配置多个域名与路径
  ## hosts:
  ## - name: cloud.mydlq.club
  ##   path: /
  ##   service: test1
  ##   port: server
  ## - name: www.mydlq.club
  ##   path: /
  ##   service: test2
  ##   port: server

  ## 配置 TLS
  ## tls:
  ## - hosts:
  ##     - www.mydlq.club
  ##   secretName: mydlq-tls